services:

    software-shinobi-dashboard:

        container_name: software-shinobi-dashboard

        image: softwareshinobi/software-shinobi-dashboard

        build: 

            context: .

            dockerfile: Dockerfile

        restart: always

        ports:
    
            - "80:80"
